service: githook

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    GITHUB_WEBHOOK_SECRET: REPLACE-WITH-YOUR-SECRET-HERE

functions:
  hello:
    handler: functions/hello.handler
    events:
      - http:
          path: /hello
          method: get
  listen:
    handler: functions/webhook_listener.handler
    events:
      - http:
          path: webhook
          method: post
          cors: true
